---
title: "Lab10"
author: "Yunguo Cai"
date: "3/30/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Example1
```{r}
set.seed(1)
x <-matrix(rnorm(20*2),ncol=2)
y <- c(rep(-1,10),rep(1,10))
x[y==1,]<-x[y==1,]+1
plot(x,col=(3-y),pch=c(21,22)[as.factor(y)])
```
```{r}
library(e1071)
dat <- data.frame(x = x, y = as.factor(y))
svmfit <- svm(y ~ ., data = dat, kernel = "linear", cost = 10, scale = FALSE)
plot(svmfit,dat)
```
```{r}
svmfit$index
summary(svmfit)
```
```{r}
svmfit <- svm(y ~ ., data = dat, kernel = "linear", cost = 0.1, scale = FALSE)
plot(svmfit, dat)
```
```{r}
svmfit$index
summary(svmfit)
```
```{r}
set.seed(1)
tune.out <- tune(svm,y~.,data=dat,kernel="linear",ranges=list(cost=c(0.001,0.01,0.1,1,5,10,100)))
summary(tune.out)
```
```{r}
bestmod <- tune.out$best.model
```

```{r}
xtest <-matrix(rnorm(20*2),ncol=2)
ytest <- sample(c(-1,1),20,rep=TRUE)
xtest[ytest==1,]=xtest[ytest==1,]+1
testdat<-data.frame(x=xtest,y=as.factor(ytest))
```

```{r}
ypred<-predict(bestmod,testdat)
table(predict=ypred,truth=testdat$y)
```
```{r}
svmfit <- svm(y ~ ., data = dat, kernel = "linear", cost = 0.01, scale = FALSE) 
ypred <- predict(svmfit, testdat)
table(predict = ypred, truth = testdat$y)
```
##Example2
```{r}
x[y == 1, ] <- x[y == 1, ] + 0.5
plot(x, col = (3-y), pch = c(21, 22)[as.factor(y)])
```

```{r}
dat <- data.frame(x = x, y = as.factor(y))
svmfit <- svm(y ~ ., data = dat, kernel = "linear", cost = 1e5)
summary(svmfit)
```

```{r}
plot(svmfit, dat)
```
```{r}
dat <- data.frame(x = x, y = as.factor(y))
svmfit <- svm(y ~ ., data = dat, kernel = "linear", cost = 1)
summary(svmfit)
```
```{r}
plot(svmfit, dat)
```
```{r}
set.seed(1)
x <- matrix(rnorm(200 * 2), ncol = 2) 
x[1:100, ] <- x[1:100, ] + 2
x[101:150, ] <- x[101:150, ] - 2
y <- c(rep(1, 150), rep(2, 50))
dat <- data.frame(x = x, y = as.factor(y))
plot(x, col = y)
```
```{r}
train<-sample(200,100)
train
```
```{r}
svmfit <- svm(y ~ ., data = dat[train, ], kernel = "radial", gamma = 1, cost = 1) 
plot(svmfit, dat[train, ])
```
```{r}
summary(svmfit)
```
```{r}
svmfit <- svm(y ~ ., data = dat[train, ], kernel = "radial", gamma = 1, cost = 1e5) 
plot(svmfit, dat[train, ])
```
```{r}
set.seed(1)
tune.out <- tune(svm, y ~ ., data = dat[train, ], kernel = "radial",
ranges = list(cost = c(0.1, 1, 10, 100, 1000), gamma = c(0.5, 1, 2, 3, 4)))
summary(tune.out)
```
```{r}
with(tune.out$performances, {
plot(error[gamma == 0.5] ~ cost[gamma == 0.5], ylim = c(.1, .35),
type = "o", col = rainbow(5)[1], ylab = "CV error", xlab = "cost")
  lines(error[gamma == 1] ~ cost[gamma == 1],
type = "o", col = rainbow(5)[2]) 
  lines(error[gamma == 2] ~ cost[gamma == 2],
type = "o", col = rainbow(5)[3]) 
  lines(error[gamma == 3] ~ cost[gamma == 3],
type = "o", col = rainbow(5)[4]) 
  lines(error[gamma == 4] ~ cost[gamma == 4],
type = "o", col = rainbow(5)[5])
})
legend("top", horiz = T, legend = c(0.5, 1:4), col = rainbow(5),
       lty = 1, cex = .75, title = "gamma")
```
```{r}
bestmod <- tune.out$best.model 
summary(bestmod)
```
```{r}
table(true = dat[-train, "y"], pred = predict(bestmod, newdata = dat[-train, ]))
```
##Multiple classes
```{r}
set.seed(1)
x <- rbind(x, matrix(rnorm(50 * 2), ncol = 2)) 
x
y <- c(y, rep(0, 50))
y
x[y == 0, 2] <- x[y == 0, 2] + 2
x
dat <- data.frame(x = x, y = as.factor(y)) 
plot(x, col = (y+1))
```
```{r}
svmfit <- svm(y ~ ., data = dat, kernel = "radial", cost = 10, gamma = 1) 
plot(svmfit, dat)
```

